# Generated by Django 5.2.3 on 2026-09-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('icon', models.CharField(default='fa-gem', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('inquiry_type', models.CharField(default='Product Inquiry', max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Faridabad', max_length=100)),
                ('state', models.CharField(default='Haryana', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery (COD)'), ('UPI', 'UPI / QR Code Transfer'), ('ONLINE', 'Online Card / NetBanking')], default='COD', max_length=20)),
                ('order_status', models.CharField(choices=[('Received', 'Order Received'), ('Processing', 'Processing & Packing'), ('Dispatched', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Received', max_length=30)),
                ('items_json', models.TextField(help_text='JSON serialized list of ordered items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(default='Faridabad', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('product_name', models.CharField(blank=True, default='Antique Decor & Plants', max_length=200)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('guests_count', models.PositiveIntegerField(default=2)),
                ('interest_area', models.CharField(default='Antiques & Artificial Plants', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Discounted / Selling Price', max_digits=10)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('material', models.CharField(help_text='e.g. Solid Brass, Distressed Teak Wood, Real-Touch Silk', max_length=150)),
                ('dimensions', models.CharField(help_text='e.g. 18in H x 12in W', max_length=100)),
                ('weight', models.CharField(blank=True, help_text='e.g. 3.2 kg', max_length=50)),
                ('room_type', models.CharField(choices=[('all', 'All Spaces'), ('living_room', 'Living Room & Foyer'), ('balcony', 'Balcony & Garden'), ('mandir', 'Mandir & Pooja Room'), ('office', 'Office & Workspace'), ('bedroom', 'Bedroom & Lounge')], default='living_room', max_length=50)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('image_url', models.URLField(max_length=500)),
                ('image_url_2', models.URLField(blank=True, max_length=500)),
                ('image_url_3', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
